### ISSUE TITLE
(JS-0125) Found the usage of undeclared variables

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Dev-Team/Website#1]
## Description
Variable that are not defined but they are being used in the code. This would give a potential errors that may break the code. It might have happen due to mistype of the variable name. &lt;!--more--&gt; Potential ReferenceErrors may result from misspellings of variable and parameter names, or accidental implicit …

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Scratch-Dev-Team/Website/issue/JS-0125/occurrences/](https://deepsource.io/gh/Scratch-Dev-Team/Website/issue/JS-0125/occurrences/)

Source of issue: @deepsourcebot

**Comment by ZI-Youtuber** [comment]
I don't think this is much of an issue but it is worth to check. I just got the code from @xItzDiamondx repository of the website

**Comment by xItzDiamondx** [comment]
Doesn't afflict any damage to the site.
