### ISSUE TITLE
Website Content

### ISSUE THREAD

**Issue by xItzDiamondx** [Scratch-Dev-Team/Website#2]
Hey, I'm having some issues. I'm just sitting down and trying to think of some good content to put on our website. Any ideas?

**Comment by ZI-Youtuber** [comment]
cool we will put this on the webiste

**Comment by xItzDiamondx** [comment]
Hey, I was at school testing. I'll develop it ASAP.

**Comment by xItzDiamondx** [comment]
> So Probably coming soon will be a page for the bookmarklets, although I am working on that. Maybe about us? also, maybe we should make it at Scratch-dev-team.github.io rather then at /website

Also, I am developing it on Visual Studio Code and testing it on Google Chrome. I'll upload it as soon as I think it is done.
